name: Clojure CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install chrome and chrome driver
      run: apt install chrome chromedriver
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
